#BNF+IAT 1.0 UTF-8;
!grammar voiceadjust;
!slot <callCmd>;
!slot <contact>;
!slot <callCmdmax>;
!slot <contactmin>;
!slot <before>;
!slot <next>;
!slot <shenzhenlkroad>;
!slot <dunhuang>;
!slot <zhangye>;
!slot <xuchangnghai>;
!slot <lanzhou>;
!slot <zhengzhouwei>;
!slot <xining>;
!slot <menyuan>;
!slot <haidong>;
!slot <chakayanhu>;
!slot <delingha>;
!slot <dachaidan>;
!slot <shuishangyadan>;
!slot <guazhou>;
!slot <yumen>;
!slot <jiayuguan>;
!slot <xuchangliandacaoyuan>;
!slot <gangcha>;
!slot <dalian>;
!slot <beijing>;
!slot <shanghai>;
!slot <guangzhou>;
!slot <shenzhen>;
!slot <zhengzhou>;
!slot <xuchang>;
!start <callStart>;
<callStart>:<callCmd>|<contact>|<callCmdmax>|<contactmin>|<before>|<next>|<shenzhenlkroad>|<dunhuang>|<zhangye>|<xuchangnghai>|<lanzhou>|<zhengzhouwei>|<xining>|<menyuan>|<haidong>|<chakayanhu>|<delingha>|<dachaidan>|<shuishangyadan>|<guazhou>|<yumen>|<jiayuguan>|<xuchangliandacaoyuan>|<gangcha>|<dalian>|<beijing>|<shanghai>|<guangzhou>|<shenzhen>|<zhengzhou>|<xuchang>;
<callCmd>:加大音量|增加音量|调大音量|音量调大|音量加大|音量增加;
<contact>:减小音量|调小音量|音量减小|音量调小;
<callCmdmax>:音量加到最大|最大音量;
<contactmin>:音量减到最小|最小音量;
<before>:上一首|上一曲;
<next>:下一首|下一曲;
<shenzhenlkroad>:丝绸之路上有什么景点|和丝绸之路相关的景点;
<dunhuang>:敦煌的景点|敦煌有什么景点;
<zhangye>:张掖的景点|张掖有什么景点;
<xuchangnghai>:青海的景点|青海有什么景点;
<lanzhou>:兰州的景点|兰州有什么景点;
<zhengzhouwei>:武威的景点|武威有什么景点;
<xining>:西宁的景点|西宁有什么景点;
<menyuan>:门源的景点|门源有什么景点;
<haidong>:海东的景点|海东有什么景点;
<chakayanhu>:茶卡盐湖的景点|茶卡盐湖有什么景点;
<delingha>:德令哈的景点|德令哈有什么景点;
<dachaidan>:大柴旦的景点|大柴旦有什么景点;
<shuishangyadan>:水上雅丹的景点|水上雅丹有什么景点;
<guazhou>:瓜州的景点|瓜州有什么景点;
<yumen>:玉门的景点|玉门有什么景点;
<jiayuguan>:嘉峪关的景点|嘉峪关有什么景点;
<xuchangliandacaoyuan>:祁连大草原的景点|祁连大草原有什么景点;
<gangcha>:刚察的景点|刚察有什么景点;
<dalian>:大连的景点|大连有什么景点;
<beijing>:北京的景点|北京有什么景点|首都的景点|首都有什么景点;
<shanghai>:上海的景点|上海有什么景点;
<guangzhou>:广州的景点|广州有什么景点;
<shenzhen>:深圳的景点|深圳有什么景点;
<zhengzhou>:郑州的景点|郑州有什么景点;
<xuchang>:许昌的景点|许昌有什么景点|魏都有什么景点|魏都的景点;
